/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'autogenerated',
      dirName: 'reference',
    },
  ],
  specification: [
    {
      type: 'autogenerated',
      dirName: 'specification',
    },
  ],
  'getting-started': [
    {
      type: 'category',
      label: 'Getting Started',
      link: { type: 'doc', id: 'getting-started/overview' },
      collapsible: false,
      items: [],
    },
  ],
  tutorials: [
    {
      type: 'autogenerated',
      dirName: 'tutorials',
    },
  ],
  explanations: [
    {
      type: 'category',
      label: 'Explanations',
      link: { type: 'doc', id: 'explanations/overview' },
      collapsible: false,
      items: ['explanations/operator'],
    },
  ],
};

module.exports = sidebars;
